[project]
name = "raa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "squarify>=0.4.4",
    "textblob>=0.19.0",
    "wordcloud>=1.9.5",
]
